Found 'grandsons' with frequency 207864
Delete 'grandsons' succeeded
NOT Found 'grandsons'
Found 'fishermans' with frequency 280414
Add 'fishermans' failed
Found 'fishermans' with frequency 280414
Autocomplete for 'fis': [ fishermans: 280414  ]
Delete 'fish' failed
Autocomplete for 'fish': [ fishermans: 280414  ]
Found 'separable' with frequency 584172
Autocomplete for 'separ': [ separable: 584172  ]
Delete 'separab' failed
Autocomplete for 'sepa': [ separable: 584172  ]
Autocomplete for 'undated': [ undated: 926271  ]