Found 'fromt' with frequency 37724
Found 'pertwee' with frequency 64182
Found 'sweltering' with frequency 145446
Found 'riaz' with frequency 65248
Found 'makinen' with frequency 45008
Found 'comission' with frequency 124886
Found 'greenbush' with frequency 269277
Found 'wwwlittlewoodscom' with frequency 30982
Found 'warpath' with frequency 84226
NOT Found 'moneyweekz'
Add 'henry' succeeded
Add 'han' succeeded
Add 'sinka' succeeded
Add 'canoo' succeeded
Add 'frendop' succeeded
Add 'silicpy' succeeded
Add 'frin' succeeded
Add 'dlen' succeeded
Add 'dnedi' succeeded
Add 'akalfr' succeeded
Autocomplete for 'fis': [ ]
Autocomplete for 'can': [ candlestick: 597438  canadas: 103105  canonized: 97556  ]
Autocomplete for 'sili': [ silicpy: 1759  ]
Autocomplete for 'hon': [ hony: 32612  ]
Autocomplete for 'ak': [ akalfr: 3232  ]
Autocomplete for 'an': [ anime: 31334688  anemia: 1860823  anus: 1472531  ]
Autocomplete for 'n': [ neumann: 1401942  nestled: 1258420  nagar: 994395  ]
Autocomplete for 'sl': [ slatkin: 94920  slunk: 40167  ]
Autocomplete for 'c': [ control: 215560453  client: 69189527  crime: 40361756  ]
Autocomplete for 'm': [ modeling: 15474514  minolta: 7160032  mib: 3731368  ]
Delete 'fromt' succeeded
Delete 'pertwee' succeeded
Delete 'sweltering' succeeded
Delete 'riaz' succeeded
Delete 'makinen' succeeded
Delete 'comission' succeeded
Delete 'greenbush' succeeded
Delete 'wwwlittlewoodscom' succeeded
Delete 'warpath' succeeded
Delete 'moneyweek' succeeded
