Found 'anti' with frequency 61227238
Add 'antisocial' succeeded
Found 'anti' with frequency 61227238
Autocomplete for 'tran': [ transport: 47041301  transactions: 23104294  transexual: 7710514  ]
Add 'transcend' succeeded
Found 'transcend' with frequency 1000000
Autocomplete for 'enc': [ encounter: 7426608  encircling: 194328  encapsulations: 65707  ]
Delete 'encyclopae' failed
NOT Found 'encyclopaedi'
Autocomplete for 'en': [ ends: 33798717  entering: 15167200  ent: 11872105  ]
Add 'encyclopaedia' succeeded
Autocomplete for 'ency': [ encyclopaedia: 331441  encyclopaedic: 54385  ]
Autocomplete for 'ox': [ oxidized: 586703  oxidizing: 343783  oxidants: 235732  ]
Found 'oxtail' with frequency 33025
Add 'oxygen' succeeded
Autocomplete for 'oxy': [ oxygenates: 87049  oxygen: 1000  ]
Delete 'oxygen' succeeded
Delete 'oxygen' failed
Autocomplete for 'blott': [ blotter: 422687  ]
Add 'distribution' succeeded
Delete 'distributes' succeeded
Autocomplete for 'dist': [ distrust: 750887  distort: 690980  distinctiveness: 221435  ]