Found 'uneasiness' with frequency 214392
Delete 'uneasiness' succeeded
NOT Found 'uneasiness'
Found 'attendants' with frequency 1171665
Add 'attendants' failed
Found 'attendants' with frequency 1171665
Autocomplete for 'outp': [ output: 55819696  ]
Delete 'output' succeeded
Autocomplete for 'outp': [ ]
Found 'reimbursed' with frequency 1344886
Autocomplete for 'reimb': [ reimbursed: 1344886  ]
Delete 'reimbur' failed
Autocomplete for 'reim': [ reimbursed: 1344886  ]
Autocomplete for 'laza': [ lazar: 321985  ]
