Found 'petite' with frequency 5796298
Found 'blinux' with frequency 54936
Found 'sulfite' with frequency 142043
Found 'butthead' with frequency 229333
Found 'creak' with frequency 124122
Found 'ved' with frequency 542056
Found 'arica' with frequency 92588
Found 'forcible' with frequency 445980
Found 'nte' with frequency 354194
NOT Found 'holbeachz'
Add 'henry' succeeded
Add 'han' succeeded
Add 'sinka' succeeded
Add 'canoo' succeeded
Add 'frendop' succeeded
Add 'silicpy' succeeded
Add 'frin' succeeded
Add 'dlen' succeeded
Add 'dnedi' succeeded
Add 'akalfr' succeeded
Autocomplete for 'fis': [ fishermans: 280414  ]
Autocomplete for 'can': [ cantons: 202309  canoo: 3232  ]
Autocomplete for 'sili': [ silicpy: 1759  ]
Autocomplete for 'hon': [ ]
Autocomplete for 'ak': [ akira: 1339862  akebono: 50056  akalfr: 3232  ]
Autocomplete for 'an': [ anon: 2273948  anvil: 936808  annexation: 912472  ]
Autocomplete for 'n': [ nst: 519918  nomic: 374700  nte: 354194  ]
Autocomplete for 'sl': [ slashes: 530627  slackened: 51486  slocombe: 36655  ]
Autocomplete for 'c': [ camps: 11712039  conformation: 1142434  chime: 1115076  ]
Autocomplete for 'm': [ mi: 48073394  manuel: 3677641  mutations: 3371343  ]
Delete 'petite' succeeded
Delete 'blinux' succeeded
Delete 'sulfite' succeeded
Delete 'butthead' succeeded
Delete 'creak' succeeded
Delete 'ved' succeeded
Delete 'arica' succeeded
Delete 'forcible' succeeded
Delete 'nte' succeeded
Delete 'holbeach' succeeded
