Found 'zach' with frequency 1914201
Found 'gruffly' with frequency 36988
Found 'buddah' with frequency 119911
Found 'casali' with frequency 37721
Found 'tachometer' with frequency 421796
Found 'genworth' with frequency 47628
Found 'spaceborne' with frequency 88329
Found 'gang' with frequency 16615190
Found 'wwwazlyrics' with frequency 31259
NOT Found 'tidallyz'
Add 'henry' succeeded
Add 'han' failed
Add 'sinka' succeeded
Add 'canoo' failed
Add 'frendop' succeeded
Add 'silicpy' succeeded
Add 'frin' succeeded
Add 'dlen' succeeded
Add 'dnedi' succeeded
Add 'akalfr' succeeded
Autocomplete for 'fis': [ fishing: 40730311  fisting: 11927246  fisheries: 8764667  ]
Autocomplete for 'can': [ cancer: 65078084  canadian: 56492789  candidate: 21635540  ]
Autocomplete for 'sili': [ siliceous: 202885  silicones: 185308  silico: 137163  ]
Autocomplete for 'hon': [ hong: 32225582  honor: 16787246  honey: 9978043  ]
Autocomplete for 'ak': [ ak: 13486949  aka: 11570453  akon: 2766008  ]
Autocomplete for 'an': [ an: 1518266684  another: 192535750  analysis: 124949540  ]
Autocomplete for 'n': [ new: 1551258643  no: 937112320  news: 755424983  ]
Autocomplete for 'sl': [ sleep: 29491537  slow: 26870240  slide: 22339084  ]
Autocomplete for 'c': [ contact: 645824184  click: 536746424  city: 390564835  ]
Autocomplete for 'm': [ more: 1544771673  most: 416210411  m: 341583838  ]
Delete 'zach' succeeded
Delete 'gruffly' succeeded
Delete 'buddah' succeeded
Delete 'casali' succeeded
Delete 'tachometer' succeeded
Delete 'genworth' succeeded
Delete 'spaceborne' succeeded
Delete 'gang' succeeded
Delete 'wwwazlyrics' succeeded
Delete 'tidally' succeeded
